### /

GET http://localhost:3000/


### create new user

POST http://localhost:3000/users
Content-Type: application/json

{
    "email":"user@email.com",
    "password":123456,
    "fistName":"Po",
    "lastName":"P"
}

### get user

GET http://localhost:3000/users/9


### get users

GET http://localhost:3000/users
